import crypto from 'node:crypto';

export const SELF_BUILD_VERSION = 'reality-self-build-v1.0';

const STATES = Object.freeze([
  'PROPOSED',
  'AUTHORIZED',
  'VALIDATING',
  'BRANCH_CREATED',
  'COMMITTED',
  'PR_OPENED',
  'AWAITING_MERGE',
  'REJECTED',
  'FAILED',
]);

function text(v) { return typeof v === 'string' ? v.trim() : ''; }
function list(v) { return Array.isArray(v) ? v : []; }
function digest(v) {
  return crypto.createHash('sha256').update(JSON.stringify(v ?? null)).digest('hex');
}
function freeze(v) { return Object.freeze(v); }

export function createSelfBuildProposal({
  requestedBy,
  objective,
  rationale = null,
  files = [],
  tests = [],
  baseRef = 'main',
  riskLevel = 'low',
  verificationPlan = [],
} = {}) {
  if (!text(requestedBy)) throw new Error('SELF_BUILD_REQUESTED_BY_REQUIRED');
  if (!text(objective)) throw new Error('SELF_BUILD_OBJECTIVE_REQUIRED');
  if (!list(files).length) throw new Error('SELF_BUILD_FILES_REQUIRED');

  const normalizedFiles = list(files).map((file) => {
    if (!text(file?.path)) throw new Error('SELF_BUILD_FILE_PATH_REQUIRED');
    if (typeof file.content !== 'string') throw new Error('SELF_BUILD_FILE_CONTENT_REQUIRED');
    return { path: file.path, content: file.content, mode: file.mode || '100644' };
  });

  return freeze({
    version: SELF_BUILD_VERSION,
    build_id: 'build:' + digest({
      requestedBy, objective, files: normalizedFiles.map(({path, content, mode}) => ({path, content, mode})),
      baseRef, tests,
    }).slice(0, 32),
    state: 'PROPOSED',
    requested_by: requestedBy,
    objective: text(objective),
    rationale,
    base_ref: text(baseRef) || 'main',
    files: normalizedFiles,
    tests: list(tests),
    risk_level: riskLevel,
    verification_plan: list(verificationPlan),
    production_merge_permitted: false,
  });
}

export function authorizeSelfBuild(proposal, {
  authorizationRef,
  authorizedBy,
  allowedOperation = 'github:write_branch',
} = {}) {
  if (!proposal?.build_id) throw new Error('SELF_BUILD_PROPOSAL_REQUIRED');
  if (proposal.state !== 'PROPOSED') throw new Error('SELF_BUILD_STATE_INVALID');
  if (!text(authorizationRef)) throw new Error('SELF_BUILD_AUTHORIZATION_REQUIRED');
  if (!text(authorizedBy)) throw new Error('SELF_BUILD_AUTHORIZED_BY_REQUIRED');

  return freeze({
    ...proposal,
    state: 'AUTHORIZED',
    authorization_ref: authorizationRef,
    authorized_by: authorizedBy,
    allowed_operation: allowedOperation,
    authorization_hash: digest({
      build_id: proposal.build_id,
      authorizationRef,
      authorizedBy,
      allowedOperation,
    }),
  });
}

export function validateSelfBuildContract(build) {
  if (!build?.build_id) throw new Error('SELF_BUILD_REQUIRED');
  if (build.state !== 'AUTHORIZED') throw new Error('SELF_BUILD_NOT_AUTHORIZED');
  if (build.production_merge_permitted !== false) throw new Error('SELF_BUILD_MERGE_BOUNDARY_VIOLATION');
  if (!text(build.authorization_ref)) throw new Error('SELF_BUILD_AUTHORIZATION_REQUIRED');
  for (const file of list(build.files)) {
    if (!text(file?.path)) throw new Error('SELF_BUILD_FILE_PATH_REQUIRED');
    if (file.path.startsWith('/') || file.path.includes('..')) throw new Error('SELF_BUILD_PATH_ESCAPE');
  }
  return true;
}

/**
 * Provider adapter contract:
 * createBranch({ baseRef, branch }) -> { branchSha }
 * writeFiles({ branch, files }) -> { commitSha }
 * openPullRequest({ branch, baseRef, title, body }) -> { number, url }
 *
 * This controller never merges, deploys, or broadens authority.
 */
export async function executeSelfBuild(build, {
  provider,
  branchPrefix = 'reality/build',
} = {}) {
  validateSelfBuildContract(build);
  if (!provider?.createBranch || !provider?.writeFiles || !provider?.openPullRequest) {
    throw new Error('SELF_BUILD_PROVIDER_REQUIRED');
  }

  const branch = `${branchPrefix}/${build.build_id.replace(/[^a-zA-Z0-9._-]/g, '-')}`;

  const branchResult = await provider.createBranch({ baseRef: build.base_ref, branch });
  const commitResult = await provider.writeFiles({
    branch,
    baseRef: build.base_ref,
    files: build.files,
    expectedBaseSha: branchResult?.branchSha || null,
    buildId: build.build_id,
  });

  const title = `Reality self-build: ${build.objective}`;
  const body = [
    '## Reality Self-Build',
    '',
    `Build: ${build.build_id}`,
    `Authorization: ${build.authorization_ref}`,
    `Base: ${build.base_ref}`,
    '',
    build.rationale ? `Rationale: ${build.rationale}` : null,
    '',
    '### Governance boundary',
    '- Generated by Reality.',
    '- Changes are isolated to a build branch.',
    '- Production merge is not permitted by this controller.',
    '- Deployment remains a separate governed capability.',
    '',
    '### Verification plan',
    ...list(build.verification_plan).map((x) => `- ${x}`),
    '',
    `Commit: ${commitResult?.commitSha || 'unknown'}`,
  ].filter((x) => x !== null).join('\n');

  const pr = await provider.openPullRequest({
    branch,
    baseRef: build.base_ref,
    title,
    body,
  });

  return freeze({
    ...build,
    state: 'PR_OPENED',
    branch,
    commit_sha: commitResult?.commitSha || null,
    pull_request: pr || null,
    production_merge_permitted: false,
  });
}

export { STATES as SELF_BUILD_STATES };
